### ISSUE TITLE
Discord link is invalid

### ISSUE THREAD

**Issue by SirYodaJedi** [yodadude2003/DATOneArchiver#1]
The discord link in the readme expired due to server boosts expiring. I'd fix it with a PR, but that would mark me as a contributor, which is a bit overkill for a simple readme fix.

As an aside, where does the "One" in DATOneArchiver come from? Is it a pun similar to `true.dat`? \
[Also, plugged your tool on my wiki.](https://ttmodding.fandom.com/wiki/DAT_file#Useful_tools)

**Comment by IsaMorphic** [comment]
> The discord link in the readme expired

Ah yes! Thank you for reminding me.  Will fix right away.

> Where does the "One" in DATOneArchiver come from?

Yeah lol, that's exactly what it is.  DAT-one-archiver as opposed to THAT-one-archiver.  

> Plugged your tool on my wiki

Thank you my dude, appreciate it :)

~ Keep it real 😎
